version: '3.7'
services:
  label-class-db:
    image: postgres:16.1-alpine3.19
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup:/backup
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "55432:5432"
volumes:
  db-data: